# Generated by Django 4.2.6 on 2023-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_categories_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
    ]
