# Generated by Django 4.2.6 on 2023-10-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
