# Generated by Django 4.2.6 on 2023-10-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.PROTECT, to='post.category'),
        ),
    ]
