# Generated by Django 4.2.6 on 2023-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
