# Generated by Django 4.2.6 on 2023-10-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_category_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='comment_count',
        ),
    ]
