# Generated by Django 4.2.6 on 2023-10-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_remove_category_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
