# Generated by Django 4.2.6 on 2023-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_alter_post_timestamp_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=50)),
                ('ministry_history', models.CharField(max_length=250)),
                ('ministry_pic', models.ImageField(upload_to='')),
                ('ministry_mission', models.CharField(max_length=250)),
                ('ministry_mission_pic', models.ImageField(upload_to='')),
                ('latest_news_title', models.CharField(max_length=250)),
                ('latest_news', models.CharField(max_length=250)),
                ('team_description', models.CharField(max_length=250)),
                ('team_member_name', models.CharField(max_length=250)),
                ('team_member_title', models.CharField(max_length=250)),
                ('team_member_profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
