# Generated by Django 4.2.6 on 2023-11-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='latest_news_title',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='ministry_history',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='ministry_mission',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='team_description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='team_member_name',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='about',
            name='team_member_title',
            field=models.TextField(max_length=250),
        ),
    ]
