# Generated by Django 4.2.6 on 2023-11-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_alter_about_latest_news_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='latest_news',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='latest_news_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='ministry_history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='ministry_mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='team_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='team_member_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='team_member_title',
            field=models.TextField(),
        ),
    ]
