# Generated by Django 4.2.6 on 2023-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_remove_teammember_team_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='latest_news_title',
            field=models.CharField(max_length=50),
        ),
    ]
