# Generated by Django 4.2.6 on 2023-11-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_alter_about_latest_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
