# Generated by Django 4.2.6 on 2023-11-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
