# Generated by Django 4.2.6 on 2023-11-14 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0039_alter_post_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img/')),
                ('quote_content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
