# Generated by Django 4.2.6 on 2023-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0040_homepage_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_slider',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
